layout_spectrum: 0.7724015
typography_spectrum: 0.3830066
color:
  saturation: 1
  lightness: 0.5985663
  brandStrength: 1
  brandColors:
    - '#000000'
    - '#ED1C24'
    - '#6D6E71'
    - '#FAD013'
    - '#FFFFFF'
  rhythmicContrast: 0.7580645
name: 'PitRoadReporter '
